#specify base image

FROM node:current-alpine3.13

RUN apk update && apk upgrade && apk add git

RUN mkdir /app

WORKDIR /app

RUN git clone https://github.com/Iansutherland/ISS_api.git .

RUN npm install

CMD node ./scraper/scrapeISS.js